services:
  checkout:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - REDIS_URL=${REDIS_URL}
      - MONGO_URI=${MONGO_URI}           # <-- Add this
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY} # <-- Add thi
    depends_on:
      - redis
    networks:
      - sfy-checkout-network

  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - sfy-checkout-network
  
networks:
  sfy-checkout-network:
    driver: bridge