services:
  checkout:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis
    networks:
      - sfy-checkout-network

  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - sfy-checkout-network
  
networks:
  sfy-checkout-network:
    driver: bridge